name: virDTL
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - beast=1.10
  - dendropy=4.5
  - entrez-direct=13.9
  - ete3=3.1
  - matplotlib=3.3
  - muscle=3.8
  - numpy=1.19
  - pandas=1.1
  - pip=21.0
  - python=3.7
  - raxml=8.2
  - scipy=1.6
  - seaborn=0.11.0
  - tqdm=4.56